# Site settings
title: Balnk
description: >
    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "example.com" # the base hostname & protocol for your site

author:
    fullname: Austris Uljan s
    googleplus: example.com
    github: example
    twitter: example
    # disqus: your_disqus_forum_shortname

# google_analytics: 'UA-XXXXXXXX-X'

# Syntax highlighting
highlightstyle: ""
styles:
    [
        agate,
        androidstudio,
        arta,
        asceti,
        atelier-cave.dark,
        atelier-cave.light,
        atelier-dune.dark,
        atelier-dune.light,
        atelier-estuary.dark,
        atelier-estuary.light,
        atelier-forest.dark,
        atelier-forest.light,
        atelier-heath.dark,
        atelier-heath.light,
        atelier-lakeside.dark,
        atelier-lakeside.light,
        atelier-plateau.dark,
        atelier-plateau.light,
        atelier-savanna.dark,
        atelier-savanna.light,
        atelier-seaside.dark,
        atelier-seaside.light,
        atelier-sulphurpool.dark,
        atelier-sulphurpool.light,
        brown_paper,
        codepen-embed,
        color-brewer,
        dark,
        darkula,
        default,
        docco,
        far,
        foundation,
        github,
        github-gist,
        googlecode,
        grayscale,
        hopscotch,
        hybrid,
        idea,
        ir_black,
        kimbie.dark,
        kimbie.light,
        magula,
        mono-blue,
        monokai,
        monokai_sublime,
        obsidian,
        paraiso.dark,
        paraiso.light,
        pojoaque,
        railscast,
        rainbow,
        school_book,
        solarized_dark,
        solarized_light,
        styles_list.txt,
        sunburst,
        tomorrow,
        tomorrow-night-blue,
        tomorrow-night-bright,
        tomorrow-night,
        tomorrow-night-eightie,
        v,
        xcode,
        zenburn,
    ]

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
highlighter: null
markdown: kramdown
